import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { CAMPS, CANDIDATES, CELL, HMIN_CM, HOURS, NX, NY, PASSES, VEHICLES, along, arrivalHour, atHour, cellOf, cellRisk, centerOf, evalRoute, frontPos, iceField, idx, lengthOf, observe, page, plan, planRoute, previousExpedition, project, replayAt, riskGrid, sampleAt, sectors, series, simulateVehicle, sigmaOf, stormAt, supportAt, thicknessAt, thicknessChange, tile, weatherAt, BLOCK_RISK, mulberry32 } from "../src/index.ts";
const ice = iceField(), risk = riskGrid(ice), A = CAMPS[0], D = CAMPS[4], from: [number, number] = [A.x, A.y], to: [number, number] = [D.x, D.y];
const analysis = JSON.parse(readFileSync(new URL("../../../model/exports/analysis.json", import.meta.url), "utf8"));
const routes = Object.fromEntries(CANDIDATES.map((c) => [c.id, plan(ice, risk, c, from, to, 20)!]));

describe("the model and the map agree", () => {
  it("one ice chunk in the Blender kit is one 5 km cell at the map's 2 km-per-unit scale, and the top surface is 4 x 4 quads", () => { expect(analysis.chunk.size).toBe(2.5); expect(analysis.chunk.size * 2).toBe(CELL); expect(analysis.chunk.topTriangles).toBe(32); const l = analysis.rover.bounds[1][2] - analysis.rover.bounds[0][2]; expect(l).toBeGreaterThan(1.6); expect(l).toBeLessThan(1.9); });
});
describe("the ice field", () => {
  it("is deterministic, bounded, and differs from year to year", () => { const b = iceField(); expect(Array.from(b.thickness)).toEqual(Array.from(ice.thickness)); expect(ice.thickness).toHaveLength(NX * NY); for (let k = 0; k < ice.thickness.length; k++) { expect(ice.thickness[k]).toBeGreaterThanOrEqual(0); expect(ice.concentration[k]).toBeGreaterThanOrEqual(0); expect(ice.concentration[k]).toBeLessThanOrEqual(1); expect(ice.confidence[k]).toBeGreaterThan(0); expect(ice.confidence[k]).toBeLessThan(1); } expect(Array.from(iceField(2025).thickness)).not.toEqual(Array.from(ice.thickness)); });
  it("has a thin lead and open water: some cells are below the rover's safe thickness and some are blocked", () => { let thin = 0, blocked = 0; for (let k = 0; k < risk.length; k++) { if (ice.thickness[k] < HMIN_CM) thin++; if (risk[k] >= BLOCK_RISK) blocked++; } expect(thin).toBeGreaterThan(20); expect(blocked).toBeGreaterThan(5); expect(blocked).toBeLessThan(thin); });
  it("risk falls as ice thickens and rises as concentration drops", () => { let last = 2; for (let t = 0; t <= 100; t += 5) { const r = cellRisk(t, 0.95); expect(r).toBeLessThanOrEqual(last + 1e-9); last = r; } expect(cellRisk(10, 0.95)).toBeGreaterThan(0.95); expect(cellRisk(90, 0.95)).toBe(0); expect(cellRisk(60, 0.4)).toBeGreaterThan(cellRisk(60, 0.95)); expect(HMIN_CM).toBeCloseTo(12 * Math.sqrt(6.5), 6); });
  it("cell geometry round-trips and bilinear thickness stays between neighbouring cells", () => { for (const [i, j] of [[0, 0], [10, 7], [39, 23]]) expect(cellOf(...centerOf(i, j))).toEqual([i, j]); const t = thicknessAt(ice, 52.5, 32.5), a = ice.thickness[idx(10, 6)], b = ice.thickness[idx(11, 6)]; expect(t).toBeGreaterThanOrEqual(Math.min(a, b) - 30); expect(thicknessAt(ice, centerOf(10, 6)[0], centerOf(10, 6)[1])).toBeCloseTo(a, 5); });
  it("sectors partition the grid: 12 sectors, every cell counted once", () => { const s = sectors(ice, risk); expect(s).toHaveLength(12); expect(s.map((x) => x.id)).toContain("D3"); for (const x of s) { expect(x.thinShare).toBeGreaterThanOrEqual(0); expect(x.thinShare).toBeLessThanOrEqual(1); } });
});
describe("weather", () => {
  it("the storm front peaks where it is, arrives when the front passes, and moves 4 km per hour", () => { const x = 100, y = 60; expect(stormAt(x, y, arrivalHour(x, y))).toBeCloseTo(1, 6); expect(stormAt(x, y, arrivalHour(x, y) + 15)).toBeLessThan(0.15); expect(frontPos(11) - frontPos(10)).toBeCloseTo(4, 9); expect(arrivalHour(20, 20)).toBeLessThan(arrivalHour(178, 98)); expect(project(100, 60)).toBe(0); });
  it("the hourly series is 72 ordered hours and the storm lowers visibility and raises the wind", () => { const s = series(100, 60); expect(s).toHaveLength(HOURS); expect(s[1].at).toBe(atHour(1)); const peak = s.reduce((a, b) => (b.storm > a.storm ? b : a)); const calm = s.reduce((a, b) => (b.storm < a.storm ? b : a)); expect(peak.visibilityKm).toBeLessThan(calm.visibilityKm); expect(peak.windMs).toBeGreaterThan(calm.windMs); expect(Math.abs(peak.hour - 35)).toBeLessThanOrEqual(1); expect(weatherAt(0, 0, 0).hour).toBe(0); });
});
describe("route planning", () => {
  it("never enters blocked cells, starts and ends exactly, and is at least the straight-line distance", () => { for (const r of Object.values(routes)) { const p = r.route.points; expect(p[0]).toEqual(from); expect(p[p.length - 1]).toEqual(to); for (const q of p.slice(1, -1)) expect(risk[idx(...cellOf(q[0], q[1]))]).toBeLessThan(BLOCK_RISK); expect(lengthOf(p)).toBeGreaterThanOrEqual(Math.hypot(to[0] - from[0], to[1] - from[1]) - 1e-6); expect(r.metrics.distanceKm).toBeCloseTo(lengthOf(p), 6); } });
  it("the three candidates trade distance for risk and support: direct is shortest and riskiest, safe is the thickest, supported has the most access", () => { const d = routes.direct.metrics, s = routes.safe.metrics, u = routes.supported.metrics; expect(d.distanceKm).toBeLessThan(s.distanceKm); expect(d.distanceKm).toBeLessThanOrEqual(u.distanceKm); expect(s.maxRisk).toBeLessThan(d.maxRisk); expect(s.minThicknessCm).toBeGreaterThan(d.minThicknessCm); expect(u.supportPct).toBeGreaterThan(d.supportPct); expect(d.thinCrossings).toBeGreaterThan(s.thinCrossings); });
  it("returns null when the water cannot be crossed, and a route is its own reverse in length", () => { const wall = new Float32Array(NX * NY).fill(1); expect(planRoute(wall, from, to, { risk: 0, support: 0 })).toBeNull(); const back = planRoute(risk, to, from, CANDIDATES[0].weights)!, fwd = routes.direct.route.points; expect(Math.abs(lengthOf(back) - lengthOf(fwd))).toBeLessThan(CELL * 2); });
  it("the planner honours its weights: more risk aversion never raises the mean risk", () => { const r = (w: number) => evalRoute(planRoute(risk, from, to, { risk: w, support: 0 })!, ice, risk, 20).meanRisk; expect(r(1)).toBeLessThanOrEqual(r(0.5) + 1e-9); expect(r(0.5)).toBeLessThanOrEqual(r(0) + 1e-9); });
  it("the storm slows a rover that is inside it: leaving later into the front lengthens the trip and exposes it", () => { const p = routes.direct.route.points, calm = evalRoute(p, ice, risk, 0), storm = evalRoute(p, ice, risk, 20); expect(calm.stormExposureH).toBe(0); expect(storm.stormExposureH).toBeGreaterThan(5); expect(storm.etaH).toBeGreaterThan(calm.etaH); expect(storm.fuelL).toBeGreaterThan(calm.fuelL); });
  it("support access is 1 near a camp and falls to 0 far from every camp", () => { expect(supportAt(A.x, A.y)).toBe(1); expect(supportAt(200, 0)).toBeLessThan(1); expect(supportAt(-500, -500)).toBe(0); });
  it("along() walks a polyline: the ends, a midpoint, and a heading east of 90 degrees", () => { const r: [number, number][] = [[0, 0], [10, 0], [10, 10]]; expect(along(r, 0)).toMatchObject({ x: 0, y: 0 }); expect(along(r, 5).headingDeg).toBeCloseTo(90, 6); expect(along(r, 15)).toMatchObject({ x: 10, y: 5 }); expect(along(r, 20)).toMatchObject({ x: 10, y: 10 }); expect(lengthOf(r)).toBe(20); });
});
describe("telemetry", () => {
  const samples = VEHICLES.map((v) => simulateVehicle(v, routes[v.routeId].route, ice, risk));
  it("has a sample every ten minutes for 72 hours and starts at the route's start", () => { for (const s of samples) { expect(s).toHaveLength(433); expect(s[1].hour - s[0].hour).toBeCloseTo(1 / 6, 3); expect([s[0].x, s[0].y]).toEqual(from); } });
  it("rovers wait until their departure, hold in a storm, and finish at the station", () => { VEHICLES.forEach((v, n) => { const s = samples[n]; for (const q of s.filter((x) => x.hour < v.departHour)) expect(q.status).toBe("Holding"); for (const q of s) if (q.status === "Holding" && q.hour >= v.departHour) expect(q.speedKmh).toBe(0); expect(s[s.length - 1].status).toBe("Arrived"); expect([s[s.length - 1].x, s[s.length - 1].y]).toEqual(to); }); expect(samples.flat().some((q) => q.status === "Holding" && q.hour > 20)).toBe(true); });
  it("fuel only falls except at a refuel, never below zero, and temperature follows the weather", () => { for (const s of samples) { for (let k = 1; k < s.length; k++) { if (s[k].status !== "Refuel" && s[k - 1].status !== "Refuel") expect(s[k].fuelPct).toBeLessThanOrEqual(s[k - 1].fuelPct + 1e-9); expect(s[k].fuelPct).toBeGreaterThanOrEqual(0); } const q = s[200]; expect(q.tempC).toBe(weatherAt(q.x, q.y, q.hour).tempC); } });
  it("a rover on the direct route is cautioned where the ice is thin", () => { expect(samples[2].some((q) => q.status === "Caution")).toBe(true); expect(samples[0].some((q) => q.status === "Caution")).toBe(false); });
  it("sampleAt picks the nearest sample, and paging is bounded and complete", () => { const s = samples[0]; expect(sampleAt(s, 12.04).hour).toBeCloseTo(12, 0); expect(sampleAt(s, -5)).toBe(s[0]); expect(sampleAt(s, 999)).toBe(s[s.length - 1]); let cursor: number | null = 0, n = 0; while (cursor !== null) { const p = page(s, 0, 72, 100, cursor); n += p.items.length; cursor = p.nextCursor; } expect(n).toBe(433); expect(page(s, 10, 12).items.every((q) => q.hour >= 10 && q.hour <= 12)).toBe(true); });
});
describe("satellites and history", () => {
  it("each pass sees only its swath; SAR is more exact than passive microwave; cloud hides optical cells", () => { const o = PASSES.map((p) => ({ p, o: observe(p, ice) })); for (const { p, o: x } of o) for (const c of x.cells) { const [cx, cy] = centerOf(c.i, c.j); expect(cx).toBeGreaterThanOrEqual(p.swath.x0); expect(cx).toBeLessThanOrEqual(p.swath.x1); expect(cy).toBeGreaterThanOrEqual(p.swath.y0); expect(cy).toBeLessThanOrEqual(p.swath.y1); } const sar = o.find((x) => x.p.id === "P1")!.o, pmw = o.find((x) => x.p.id === "P3")!.o, clear = o.find((x) => x.p.id === "P2")!.o, cloudy = o.find((x) => x.p.id === "P5")!.o; expect(sar.meanAbsErrorCm).toBeLessThan(pmw.meanAbsErrorCm); expect(cloudy.seen / cloudy.cells.length).toBeLessThan(clear.seen / clear.cells.length); expect(sigmaOf(PASSES[4])).toBeGreaterThan(sigmaOf(PASSES[1])); expect(observe(PASSES[0], ice).meanAbsErrorCm).toBe(sar.meanAbsErrorCm); });
  it("the 2025 expedition is replayed along its own path and the ice has thinned since", () => { const h = previousExpedition(); expect(replayAt(h.route, 0)).toMatchObject({ x: from[0], y: from[1], km: 0 }); const end = replayAt(h.route, 1); expect([end.x, end.y]).toEqual(to); expect(Date.parse(end.at)).toBeGreaterThan(Date.parse(replayAt(h.route, 0.5).at)); expect(thicknessChange(h.route, h.ice, ice)).toBeLessThan(0); });
});
describe("ice tiles", () => {
  it("every tile is 10 x 6 cells; z2 tiles carry the raw cells; coarser zooms average them", () => { const t = tile(ice, risk, 2, 1, 2); expect(t.thicknessCm).toHaveLength(60); expect(t.cellKm).toBe(5); expect(t.thicknessCm[0]).toBeCloseTo(ice.thickness[idx(10, 12)], 0); const z0 = tile(ice, risk, 0, 0, 0); expect(z0.thicknessCm).toHaveLength(60); expect(z0.cellKm).toBe(20); const mean = (a: ArrayLike<number>) => Array.from(a).reduce((x, y) => x + y, 0) / a.length; expect(mean(z0.thicknessCm)).toBeCloseTo(mean(ice.thickness), 0); });
  it("rejects tiles outside the pyramid", () => { expect(() => tile(ice, risk, 3, 0, 0)).toThrow(RangeError); expect(() => tile(ice, risk, 1, 2, 0)).toThrow(/x and y/); expect(() => tile(ice, risk, 0, -1, 0)).toThrow(RangeError); void mulberry32; });
});
