"use client";
import { useMemo } from "react";
import gsap from "gsap";
import { CAMPS, CANDIDATES, CELL, HMIN_CM, HOURS, NX, NY, arrivalHour, atHour, cellOf, cellRisk, centerOf, evalRoute, frontPos, idx, lengthOf, observe, planRoute, replayAt, sampleAt, sectors, sigmaOf, thicknessAt, thicknessChange, FRONT } from "@polaris/domain";
import type { Weights } from "@polaris/schemas";
import { LAYERS, PALETTE, layerColor, layerValue, rampThickness, rampRisk, rampConc, type Data, type Layer } from "../data";
import { live, set, state, useStore, VIEWS, type Cam, type View } from "../store";

const go = (v: View) => { if (v !== state.view) { set({ view: v, fly: null }); history.replaceState(null, "", `#${v}`); } };
const f0 = (x: number) => Math.round(x).toString(), f1 = (x: number) => (Math.round(x * 10) / 10).toString(), f2 = (x: number) => (Math.round(x * 100) / 100).toFixed(2), rgb = (c: number[]) => `rgb(${c[0]},${c[1]},${c[2]})`;
const when = (h: number) => atHour(h).replace("T", " ").slice(0, 16) + "Z";
const Disclaimer = () => <p className="fine">Synthetic ice, weather and telemetry. Not for real navigation or ice travel.</p>;
const NAME: Record<string, string> = { direct: "Direct", safe: "Safe ice", supported: "Supported", custom: "Custom" };
/** A route for a candidate id or the custom weights, planned in the browser with the same domain code as the API. */
export function routeFor(id: string, d: Data, custom: Weights): [number, number][] | null { if (id === "custom") return planRoute(d.risk, [CAMPS[0].x, CAMPS[0].y], [CAMPS[4].x, CAMPS[4].y], custom); return d.routes.find((r) => r.id === id)?.points ?? null; }
const stormPolygon = (hour: number) => { const s = frontPos(hour), c = [100 + FRONT.dirX * s, 60 + FRONT.dirY * s], px = -FRONT.dirY, py = FRONT.dirX, a = FRONT.sigmaKm * 1.6; const pt = (k: number, o: number) => `${c[0] + px * k + FRONT.dirX * o},${120 - (c[1] + py * k + FRONT.dirY * o)}`; return `${pt(-300, -a)} ${pt(300, -a)} ${pt(300, a)} ${pt(-300, a)}`; };

export function MapSvg({ data }: { data: Data }) {
  const s = useStore(), d = data, pass = d.passes.find((p) => p.id === s.selPass)!, obs = useMemo(() => (s.view === "satellite" ? observe(pass, d.ice) : null), [s.view, pass, d.ice]);
  const prev = s.replay.on ? replayAt(d.previous.route, s.replay.f) : null, rts = [s.routeA, s.routeB, s.activeRoute].filter((v, i, a) => a.indexOf(v) === i);
  const cells = useMemo(() => { const out = []; for (let j = 0; j < NY; j++) for (let i = 0; i < NX; i++) { const k = idx(i, j), c = layerColor(s.layer, k, d); out.push(<rect key={k} x={i * CELL} y={(NY - 1 - j) * CELL} width={CELL} height={CELL} fill={rgb(c)} className="cell" data-risk={d.risk[k] >= 0.55 ? "high" : undefined} onClick={() => set({ selCell: [i, j] })} />); } return out; }, [s.layer, d]);
  return (
    <svg className="map" viewBox="0 0 200 120" role="img" aria-label="Map of the synthetic ice region, north up" data-testid="map">
      <rect width={200} height={120} fill={PALETTE.night} />{cells}
      {s.overlayRisk && s.layer !== "risk" && <g className="riskov" data-testid="risk-overlay">{Array.from({ length: NX * NY }, (_, k) => d.risk[k] > 0.4 ? <rect key={k} x={(k % NX) * CELL} y={(NY - 1 - Math.floor(k / NX)) * CELL} width={CELL} height={CELL} fill={PALETTE.violet} opacity={Math.min(0.85, d.risk[k])} pointerEvents="none" /> : null)}</g>}
      {obs && s.showDiff && obs.cells.map((c) => c.observedCm === null ? null : <rect key={`${c.i}-${c.j}`} x={c.i * CELL} y={(NY - 1 - c.j) * CELL} width={CELL} height={CELL} fill={c.observedCm - c.modelCm >= 0 ? PALETTE.green : PALETTE.violet} opacity={Math.min(0.8, Math.abs(c.observedCm - c.modelCm) / 25)} pointerEvents="none" />)}
      {s.view === "satellite" && <rect x={pass.swath.x0} y={120 - pass.swath.y1} width={pass.swath.x1 - pass.swath.x0} height={pass.swath.y1 - pass.swath.y0} className="swath" data-testid="swath" />}
      {s.showStorm && <g className="storm" data-testid="storm-front" data-hour={s.hour}><polygon points={stormPolygon(s.hour)} /></g>}
      {rts.map((id, n) => { const pts = routeFor(id, d, s.custom); return pts ? <polyline key={id} points={pts.map(([x, y]) => `${x},${120 - y}`).join(" ")} className={`route ${id === s.activeRoute ? "active" : ""} r${n % 3}`} data-testid={`route-line-${id}`} /> : null; })}
      {prev && <><polyline points={d.previous.route.points.map(([x, y]) => `${x},${120 - y}`).join(" ")} className="route prev" data-testid="prev-line" /><circle cx={prev.x} cy={120 - prev.y} r={2.2} className="prevdot" data-testid="prev-dot" /></>}
      {s.selCell && <rect x={s.selCell[0] * CELL} y={(NY - 1 - s.selCell[1]) * CELL} width={CELL} height={CELL} className="sel" pointerEvents="none" />}
      {d.camps.map((c) => <g key={c.id} className={`camp ${c.kind}`} transform={`translate(${c.x} ${120 - c.y})`} data-testid={`camp-${c.id}`}><rect x={-1.4} y={-1.4} width={2.8} height={2.8} /><text y={-2.6} textAnchor="middle">{c.id}</text></g>)}
      {d.vehicles.map((v) => { const t = sampleAt(v.samples, s.hour); return <g key={v.id} className={`rover ${s.selVehicle === v.id ? "sel" : ""}`} transform={`translate(${t.x} ${120 - t.y}) rotate(${t.headingDeg})`} data-testid={`rover-${v.id}`} data-status={t.status} onClick={() => set({ selVehicle: v.id })}><polygon points="0,-2.6 1.6,1.6 -1.6,1.6" fill={v.color} /></g>; })}
    </svg>
  );
}
function TimeBar() {
  const s = useStore();
  return (<div className="timebar"><button className="btn" onClick={() => set({ playing: !s.playing })} aria-pressed={s.playing} data-testid="play">{s.playing ? "Pause" : "Play"}</button><label>Hour <output data-testid="hour-out">{f1(s.hour)}</output><input type="range" min={0} max={HOURS - 0.25} step={0.25} value={s.hour} onChange={(e) => set({ hour: Number(e.target.value) })} data-testid="hour" aria-label="Hour of the 72 hour window" /></label><span className="when" data-testid="when">{when(s.hour)}</span></div>);
}
function Legend({ layer }: { layer: Layer }) { const rp = layer === "thickness" ? rampThickness : layer === "risk" ? rampRisk : rampConc, lab = layer === "thickness" ? ["0", "110 cm"] : layer === "risk" ? ["0 safe", "1 broken"] : layer === "concentration" ? ["0", "1"] : ["low", "high"]; return <div className="legend" data-testid="legend"><span>{lab[0]}</span><i style={{ background: `linear-gradient(90deg, ${[0, 0.25, 0.5, 0.75, 1].map((t) => rgb(rp(t))).join(",")})` }} /><span>{lab[1]}</span></div>; }

function MapView({ data }: { data: Data }) {
  const s = useStore();
  return (<section aria-labelledby="h-m"><h2 id="h-m">Expedition map</h2><p className="lede">Nordvik Strait crossing (fictional), 200 by 120 km. Routes etch into the ice, camps hold supplies, rovers move with the hour. North is up.</p>
    <MapSvg data={data} /><TimeBar />
    <div className="row2"><label className="chk"><input type="checkbox" checked={s.showStorm} onChange={(e) => set({ showStorm: e.target.checked })} data-testid="show-storm" /> Storm front</label><label className="chk"><input type="checkbox" checked={s.overlayRisk} onChange={(e) => set({ overlayRisk: e.target.checked })} data-testid="overlay-risk" /> Ice risk overlay</label></div>
    <h3>Camps and rovers at this hour</h3><table className="tbl" data-testid="roster"><tbody>{data.camps.map((c) => <tr key={c.id}><th scope="row">{c.name}</th><td>{c.kind}</td><td>{c.x}, {c.y} km</td></tr>)}{data.vehicles.map((v) => { const t = sampleAt(v.samples, s.hour); return <tr key={v.id} data-testid={`roster-${v.id}`}><th scope="row">{v.name} ({v.id})</th><td>{t.status}</td><td>{f0(t.x)}, {f0(t.y)} km, fuel {f0(t.fuelPct)}%</td></tr>; })}</tbody></table><Disclaimer /></section>);
}
function IceView({ data }: { data: Data }) {
  const s = useStore(), sec = useMemo(() => sectors(data.ice, data.risk), [data]), k = s.selCell ? idx(...s.selCell) : null, th = k === null ? null : data.ice.thickness[k];
  return (<section aria-labelledby="h-i"><h2 id="h-i">Ice conditions</h2><p className="lede">Thickness, risk, concentration and confidence on a 5 km grid. Risk compares thickness with what this 6.5 t rover needs ({f1(HMIN_CM)} cm in this demo's invented rule).</p>
    <div className="row2"><label>Layer<select value={s.layer} onChange={(e) => set({ layer: e.target.value as Layer })} data-testid="layer">{LAYERS.map((l) => <option key={l.id} value={l.id}>{l.label}</option>)}</select></label><label className="chk"><input type="checkbox" checked={s.overlayRisk} onChange={(e) => set({ overlayRisk: e.target.checked })} data-testid="overlay-risk" /> Risk overlay</label></div>
    <MapSvg data={data} /><Legend layer={s.layer} />
    <dl className="spec" data-testid="inspector">{k === null ? <div><dt>Cell</dt><dd>Click the map</dd></div> : <><div><dt>Cell</dt><dd data-testid="cell-id">{s.selCell![0]}, {s.selCell![1]} ({centerOf(...s.selCell!).join(", ")} km)</dd></div><div><dt>Thickness</dt><dd data-testid="cell-thickness">{f0(th!)} cm</dd></div><div><dt>Risk</dt><dd data-testid="cell-risk">{f2(data.risk[k])}</dd></div><div><dt>Concentration</dt><dd data-testid="cell-conc">{f2(data.ice.concentration[k])}</dd></div><div><dt>Confidence</dt><dd data-testid="cell-conf">{f2(data.ice.confidence[k])}</dd></div><div><dt>Rover</dt><dd data-testid="cell-safe" data-safe={th! >= HMIN_CM}>{th! >= HMIN_CM ? "thick enough" : "too thin"}</dd></div></>}</dl>
    <h3>By sector (50 km)</h3><table className="tbl" data-testid="sectors"><thead><tr><th>Sector</th><th>Mean cm</th><th>Risk</th><th>Thin</th></tr></thead><tbody>{sec.map((x) => <tr key={x.id} data-testid={`sector-${x.id}`}><th scope="row">{x.id}</th><td>{f0(x.meanThicknessCm)}</td><td>{f2(x.meanRisk)}</td><td>{f0(x.thinShare * 100)}%</td></tr>)}</tbody></table><Disclaimer /></section>);
}
function WeatherView({ data }: { data: Data }) {
  const s = useStore(), W = data.weather, route = routeFor(s.activeRoute, data, s.custom)!, m = useMemo(() => evalRoute(route, data.ice, data.risk, s.departHour), [route, data, s.departHour]), x = (h: number) => (h / (HOURS - 1)) * 240, line = (f: (w: typeof W[0]) => number, lo: number, hi: number) => W.map((w, i) => `${i ? "L" : "M"}${x(w.hour)} ${70 - ((f(w) - lo) / (hi - lo)) * 64}`).join(" "), now = W[Math.max(0, Math.min(HOURS - 1, Math.round(s.hour)))];
  return (<section aria-labelledby="h-w"><h2 id="h-w">Weather timeline</h2><p className="lede">A storm front crosses the region from the north-west to the south-east at {FRONT.speedKmh} km/h. Scrub or play it and watch it meet the route.</p>
    <MapSvg data={data} /><TimeBar />
    <svg className="wxchart" viewBox="0 0 240 76" role="img" aria-label="Wind, visibility and temperature over 72 hours" data-testid="wx-chart" onClick={(e) => { const r = (e.currentTarget as SVGSVGElement).getBoundingClientRect(); set({ hour: Math.round(((e.clientX - r.left) / r.width) * (HOURS - 1) * 4) / 4 }); }}><path d={line((w) => w.storm, 0, 1) + " L240 70 L0 70 Z"} className="area" /><path d={line((w) => w.windMs, 0, 30)} className="wind" /><path d={line((w) => w.visibilityKm, 0, 30)} className="vis" /><path d={line((w) => w.tempC, -32, -16)} className="temp" /><line x1={x(s.hour)} x2={x(s.hour)} y1={0} y2={72} className="cursor" /></svg>
    <dl className="spec"><div><dt>Wind</dt><dd data-testid="wx-wind">{f1(now.windMs)} m/s</dd></div><div><dt>Visibility</dt><dd data-testid="wx-vis">{f1(now.visibilityKm)} km</dd></div><div><dt>Temperature</dt><dd>{f1(now.tempC)} °C</dd></div><div><dt>Storm at centre</dt><dd data-testid="wx-storm">{f2(now.storm)}</dd></div></dl>
    <h3>The route against the front</h3><div className="row2"><label>Route<select value={s.activeRoute} onChange={(e) => set({ activeRoute: e.target.value })} data-testid="wx-route">{["direct", "safe", "supported", "custom"].map((id) => <option key={id} value={id}>{NAME[id]}</option>)}</select></label><label>Leave at hour <output>{s.departHour}</output><input type="range" min={0} max={48} step={1} value={s.departHour} onChange={(e) => set({ departHour: Number(e.target.value) })} data-testid="depart" /></label></div>
    <p className="status" data-testid="wx-exposure" role="status">{NAME[s.activeRoute]} route leaving at hour {s.departHour}: {f1(m.stormExposureH)} h inside the front (storm above 0.35), {f1(m.etaH)} h underway.</p>
    <table className="tbl" data-testid="arrivals"><thead><tr><th>Camp</th><th>Front arrives</th></tr></thead><tbody>{data.camps.map((c) => <tr key={c.id} data-testid={`arrival-${c.id}`}><th scope="row">{c.name}</th><td>hour {f1(arrivalHour(c.x, c.y))} · {when(arrivalHour(c.x, c.y)).slice(5)}</td></tr>)}</tbody></table><Disclaimer /></section>);
}
function RoversView({ data }: { data: Data }) {
  const s = useStore(), v = data.vehicles.find((x) => x.id === s.selVehicle)!, t = sampleAt(v.samples, s.hour), prev = replayAt(data.previous.route, s.replay.f), then = thicknessAt({ ...data.ice, thickness: data.previous.thickness }, prev.x, prev.y), now = thicknessAt(data.ice, prev.x, prev.y), change = useMemo(() => thicknessChange(data.previous.route, { ...data.ice, thickness: data.previous.thickness }, data.ice), [data]);
  const spark = v.samples.map((q, i) => `${i ? "L" : "M"}${(q.hour / (HOURS)) * 240} ${50 - (q.fuelPct / 100) * 46}`).join(" ");
  return (<section aria-labelledby="h-r"><h2 id="h-r">Vehicle telemetry</h2><p className="lede">Three rovers on three routes. Each slows with risk and storm, holds when the storm is strong and refuels at camps.</p>
    <MapSvg data={data} /><TimeBar />
    <div className="chips" role="group" aria-label="Rovers">{data.vehicles.map((x) => <button key={x.id} className={`chip ${x.id === v.id ? "on" : ""}`} onClick={() => set({ selVehicle: x.id })} aria-pressed={x.id === v.id} data-testid={`veh-${x.id}`} style={{ borderColor: x.id === v.id ? x.color : undefined }}>{x.name} · {sampleAt(x.samples, s.hour).status}</button>)}</div>
    <dl className="spec" data-testid="telemetry"><div><dt>Status</dt><dd data-testid="tel-status">{t.status}</dd></div><div><dt>Speed</dt><dd data-testid="tel-speed">{f1(t.speedKmh)} km/h</dd></div><div><dt>Fuel</dt><dd data-testid="tel-fuel">{f1(t.fuelPct)}%</dd></div><div><dt>Outside</dt><dd data-testid="tel-temp">{f1(t.tempC)} °C</dd></div><div><dt>Position</dt><dd data-testid="tel-pos">{f0(t.x)}, {f0(t.y)} km</dd></div><div><dt>Route</dt><dd>{NAME[v.routeId]}, left hour {v.departHour}</dd></div></dl>
    <svg className="spark" viewBox="0 0 240 54" role="img" aria-label={`Fuel level of ${v.name} over 72 hours`} data-testid="fuel-chart"><path d={spark} /><line x1={(s.hour / HOURS) * 240} x2={(s.hour / HOURS) * 240} y1={0} y2={54} /></svg>
    <h3>Replay the 2025 expedition</h3><div className="row2"><label className="chk"><input type="checkbox" checked={s.replay.on} onChange={(e) => set({ replay: { ...s.replay, on: e.target.checked } })} data-testid="replay-toggle" /> Show and replay</label><label>Progress <output>{f0(s.replay.f * 100)}%</output><input type="range" min={0} max={1} step={0.01} value={s.replay.f} disabled={!s.replay.on} onChange={(e) => set({ replay: { ...s.replay, f: Number(e.target.value) } })} data-testid="replay-f" /></label></div>
    {s.replay.on && <dl className="spec" data-testid="replay"><div><dt>Date</dt><dd data-testid="replay-date">{prev.at.slice(0, 16).replace("T", " ")}Z</dd></div><div><dt>Distance</dt><dd data-testid="replay-km">{f0(prev.km)} km of {f0(lengthOf(data.previous.route.points))}</dd></div><div><dt>Ice then / now</dt><dd data-testid="replay-ice">{f0(then)} / {f0(now)} cm</dd></div><div><dt>Mean change on the path</dt><dd data-testid="replay-change">{f1(change)} cm</dd></div></dl>}<Disclaimer /></section>);
}
function SatelliteView({ data }: { data: Data }) {
  const s = useStore(), p = data.passes.find((x) => x.id === s.selPass)!, o = useMemo(() => observe(p, data.ice), [p, data.ice]);
  return (<section aria-labelledby="h-s"><h2 id="h-s">Satellite observations</h2><p className="lede">Six synthetic passes. Each sensor sees part of the region with its own noise; cloud hides the optical one. The map shows the selected swath.</p>
    <MapSvg data={data} />
    <table className="tbl" data-testid="passes"><thead><tr><th>Pass</th><th>Sensor</th><th>Hour</th><th>Cloud</th></tr></thead><tbody>{data.passes.map((x) => <tr key={x.id} className={x.id === p.id ? "on" : ""}><th scope="row"><button className="link" onClick={() => set({ selPass: x.id })} aria-pressed={x.id === p.id} data-testid={`pass-${x.id}`}>{x.id}</button></th><td>{x.sensor}</td><td>{x.hour}</td><td>{f0(x.cloud * 100)}%</td></tr>)}</tbody></table>
    <dl className="spec" data-testid="obs"><div><dt>Instrument</dt><dd>{p.label}, {p.resolutionKm} km</dd></div><div><dt>Cells seen</dt><dd data-testid="obs-seen">{o.seen} of {o.cells.length}</dd></div><div><dt>Noise (sigma)</dt><dd data-testid="obs-sigma">{f1(sigmaOf(p))} cm</dd></div><div><dt>Mean error vs model</dt><dd data-testid="obs-mae">{f1(o.meanAbsErrorCm)} cm</dd></div><div><dt>Bias</dt><dd>{f1(o.biasCm)} cm</dd></div></dl>
    <label className="chk"><input type="checkbox" checked={s.showDiff} onChange={(e) => set({ showDiff: e.target.checked })} data-testid="show-diff" /> Show observed minus model on the map (green thicker, violet thinner)</label><Disclaimer /></section>);
}
function RoutesView({ data }: { data: Data }) {
  const s = useStore(), ids = [...CANDIDATES.map((c) => c.id), "custom"], ev = (id: string) => { const pts = routeFor(id, data, s.custom); return pts ? { pts, m: evalRoute(pts, data.ice, data.risk, s.departHour) } : null; }, A = useMemo(() => ev(s.routeA), [s.routeA, s.custom, s.departHour, data]), B = useMemo(() => ev(s.routeB), [s.routeB, s.custom, s.departHour, data]);  // eslint-disable-line react-hooks/exhaustive-deps
  const rows: [string, string, (m: NonNullable<typeof A>["m"]) => number, (n: number) => string, boolean][] = [["Distance", "dist", (m) => m.distanceKm, (n) => `${f0(n)} km`, true], ["Mean risk", "risk", (m) => m.meanRisk, f2, true], ["Max risk", "maxrisk", (m) => m.maxRisk, f2, true], ["Thinnest ice", "minice", (m) => m.minThicknessCm, (n) => `${f0(n)} cm`, false], ["Thin crossings", "thin", (m) => m.thinCrossings, f0, true], ["Time underway", "eta", (m) => m.etaH, (n) => `${f1(n)} h`, true], ["Fuel", "fuel", (m) => m.fuelL, (n) => `${f0(n)} L`, true], ["Support access", "support", (m) => m.supportPct, (n) => `${f0(n * 100)}%`, false], ["Hours in the storm", "storm", (m) => m.stormExposureH, (n) => `${f1(n)} h`, true]];
  const sel = (key: "routeA" | "routeB") => <select value={s[key]} onChange={(e) => set({ [key]: e.target.value } as never)} data-testid={key === "routeA" ? "route-a" : "route-b"} aria-label={key === "routeA" ? "Route A" : "Route B"}>{ids.map((id) => <option key={id} value={id}>{NAME[id]}</option>)}</select>;
  const fly = (id: string) => { const pts = routeFor(id, data, s.custom); if (!pts) return; set({ fly: id, activeRoute: id, cam: "auto" }); live.flyT = 0; gsap.to(live, { flyT: 1, duration: s.reduced ? 0.01 : 9, ease: "power1.inOut", overwrite: true, onComplete: () => set({ fly: null }) }); };
  const verdict = A && B ? `${NAME[s.routeB]} ${B.m.maxRisk < A.m.maxRisk ? "is safer" : "is not safer"} than ${NAME[s.routeA]} (max risk ${f2(A.m.maxRisk)} to ${f2(B.m.maxRisk)}) and ${B.m.distanceKm > A.m.distanceKm ? "longer" : "shorter or equal"} by ${f0(Math.abs(B.m.distanceKm - A.m.distanceKm))} km.` : "";
  return (<section aria-labelledby="h-t"><h2 id="h-t">Route planner</h2><p className="lede">Compare two candidates from Base Camp A to Station D on risk, distance and support access. The better value in each row is marked.</p>
    <MapSvg data={data} />
    <div className="row2"><label>Route A{sel("routeA")}</label><label>Route B{sel("routeB")}</label><label>Leave at hour <output>{s.departHour}</output><input type="range" min={0} max={48} step={1} value={s.departHour} onChange={(e) => set({ departHour: Number(e.target.value) })} data-testid="depart" /></label></div>
    {(s.routeA === "custom" || s.routeB === "custom") && <div className="row2" data-testid="custom-weights"><label>Risk aversion <output>{f1(s.custom.risk)}</output><input type="range" min={0} max={1} step={0.1} value={s.custom.risk} onChange={(e) => set({ custom: { ...s.custom, risk: Number(e.target.value) } })} data-testid="w-risk" /></label><label>Support access <output>{f1(s.custom.support)}</output><input type="range" min={0} max={1} step={0.1} value={s.custom.support} onChange={(e) => set({ custom: { ...s.custom, support: Number(e.target.value) } })} data-testid="w-support" /></label></div>}
    {A && B && <table className="tbl" data-testid="compare"><thead><tr><th /><th>A · {NAME[s.routeA]}</th><th>B · {NAME[s.routeB]}</th></tr></thead><tbody>{rows.map(([label, id, f, fmt, lowerBetter]) => { const a = f(A.m), b = f(B.m), better = a === b ? "" : (a < b) === lowerBetter ? "a" : "b"; return <tr key={id}><th scope="row">{label}</th><td data-testid={`cmp-a-${id}`} className={better === "a" ? "win" : ""}>{fmt(a)}</td><td data-testid={`cmp-b-${id}`} className={better === "b" ? "win" : ""}>{fmt(b)}</td></tr>; })}</tbody></table>}
    <p className="status" data-testid="route-verdict" role="status">{verdict}</p>
    <div className="row2"><button className="btn" onClick={() => fly(s.routeA)} data-testid="fly-a">Fly route A</button><button className="btn" onClick={() => fly(s.routeB)} data-testid="fly-b">Fly route B</button><button className="btn primary" onClick={() => set({ activeRoute: s.routeB })} data-testid="select-b" aria-pressed={s.activeRoute === s.routeB}>Select B as the plan</button></div>
    <p className="fine" data-testid="active-route">Plan: {NAME[s.activeRoute]}{s.fly ? " (camera is flying it)" : ""}.</p><Disclaimer /></section>);
}
const CAMS: [Cam, string][] = [["auto", "Auto"], ["map", "Map"], ["oblique", "Oblique"], ["rover", "Rover"]];
export default function Panels({ data }: { data: Data }) {
  const s = useStore(), idxv = VIEWS.findIndex((v) => v.id === s.view), V = s.view;
  return (
    <div className="ui" data-testid="hud">
      <header className="top"><span className="brand">POLARIS</span><span className="aurora-line" aria-hidden /><div className="cams" role="group" aria-label="Camera">{CAMS.map(([k, l]) => <button key={k} className={`btn ghost ${s.cam === k ? "on" : ""}`} aria-pressed={s.cam === k} onClick={() => set({ cam: k, fly: null })} data-testid={`cam-${k}`}>{l}</button>)}</div><button className="btn ghost" aria-pressed={s.pauseMotion} onClick={() => set({ pauseMotion: !s.pauseMotion })} data-testid="pause-motion">{s.pauseMotion ? "Resume motion" : "Pause motion"}</button></header>
      <nav className="rail" aria-label="Views">{VIEWS.map((v, i) => <button key={v.id} className={i === idxv ? "on" : ""} aria-current={i === idxv ? "page" : undefined} onClick={() => go(v.id)} data-testid={`nav-${v.id}`}><b>{v.label}</b><small>{v.blurb}</small></button>)}</nav>
      <main className={`panel ${s.reduced ? "" : "wipe"}`} key={V} tabIndex={-1}>{V === "map" && <MapView data={data} />}{V === "ice" && <IceView data={data} />}{V === "weather" && <WeatherView data={data} />}{V === "rovers" && <RoversView data={data} />}{V === "satellite" && <SatelliteView data={data} />}{V === "routes" && <RoutesView data={data} />}</main>
    </div>
  );
}
void cellOf; void cellRisk;
