// POLARIS API: the blueprint's section 12 contract. Ice is served as bounded tiles, telemetry is paged, route planning is idempotent, and the live channel is a WebSocket (the one genuinely live thing).
import { createServer, type IncomingMessage, type ServerResponse, type Server } from "node:http";
import { WebSocketServer } from "ws";
import { CAMPS, CANDIDATES, DEFAULT_DEPART, HOURS, NX, NY, VEHICLES, cellOf, centerOf, iceField, idx, page, plan, riskGrid, sampleAt, series, simulateVehicle, tile, weatherAt } from "../../../packages/domain/src/index.ts";
import type { Camp, Route, TelemetrySample } from "../../../packages/schemas/src/index.ts";
export const openapi = { openapi: "3.1.0", info: { title: "POLARIS API", version: "1.0.0", description: "Synthetic polar expedition data. Not for real navigation." }, paths: {
  "/v1/expeditions/{id}": { get: { summary: "The expedition with its camps, rovers and the three candidate routes" } }, "/v1/routes/plan": { post: { summary: "Plan a route between two camps or points with risk and support weights; Idempotency-Key required" } },
  "/v1/ice/tiles/{z}/{x}/{y}": { get: { summary: "A 10 x 6 cell tile of ice thickness, concentration, confidence and risk; z 0 to 2" } }, "/v1/weather": { get: { summary: "Hourly weather at a point; ?x&y&from&to" } },
  "/v1/vehicles": { get: { summary: "Rovers with their telemetry at ?hour" } }, "/v1/vehicles/{id}/telemetry": { get: { summary: "Paged telemetry; ?from&to&limit&cursor" } }, "/v1/vehicles/live": { get: { summary: "WebSocket upgrade: one message per rover every 250 ms, hours advance 1 per second" } } } };
export function build() {
  const ice = iceField(), risk = riskGrid(ice), a = CAMPS[0], d = CAMPS[4], planned = CANDIDATES.map((c) => plan(ice, risk, c, [a.x, a.y], [d.x, d.y], DEFAULT_DEPART)!), byId = Object.fromEntries(planned.map((p) => [p.route.id, p.route])) as Record<string, Route>;
  const tele: Record<string, TelemetrySample[]> = Object.fromEntries(VEHICLES.map((v) => [v.id, simulateVehicle(v, byId[v.routeId], ice, risk)])), seen = new Map<string, unknown>(), plans = new Map<string, unknown>(); let seq = 1;
  const send = (res: ServerResponse, code: number, body: unknown) => { res.writeHead(code, { "content-type": "application/json", "access-control-allow-origin": "*", "access-control-allow-headers": "content-type,idempotency-key", "access-control-allow-methods": "GET,POST,OPTIONS" }); res.end(JSON.stringify(body)); };
  const err = (res: ServerResponse, code: number, error: string) => send(res, code, { error });
  async function body(req: IncomingMessage) { let s = ""; for await (const c of req) { s += c; if (s.length > 10_000) throw new RangeError("body too large"); } return s ? JSON.parse(s) : {}; }
  const num = (v: string | null, dflt: number) => (v === null ? dflt : Number(v));
  const point = (v: unknown): [number, number] | null => { if (typeof v === "string") { const c = CAMPS.find((x: Camp) => x.id === v); return c ? [c.x, c.y] : null; } if (Array.isArray(v) && v.length === 2 && v.every((n) => typeof n === "number" && Number.isFinite(n)) && v[0] >= 0 && v[0] <= NX * 5 && v[1] >= 0 && v[1] <= NY * 5) return [v[0], v[1]]; return null; };
  const server: Server = createServer(async (req, res) => {
    try {
      const u = new URL(req.url ?? "/", "http://x"), p = u.pathname.replace(/\/+$/, "") || "/", m = req.method ?? "GET"; let g: RegExpMatchArray | null;
      if (m === "OPTIONS") return send(res, 204, {}); if (p === "/openapi.json") return send(res, 200, openapi); if (p === "/healthz") return send(res, 200, { ok: true });
      if ((g = p.match(/^\/v1\/expeditions\/([\w-]+)$/)) && m === "GET") { if (g[1] !== "exp-2026-nordvik") return err(res, 404, "no such expedition"); return send(res, 200, { id: g[1], name: "Nordvik Strait crossing (fictional)", region: "Synthetic polar strait, 200 x 120 km", start: "2026-03-14", end: "2026-03-17", camps: CAMPS, vehicles: VEHICLES, routes: planned.map((x) => ({ id: x.route.id, name: x.route.name, weights: x.route.weights, metrics: x.metrics })) }); }
      if ((g = p.match(/^\/v1\/ice\/tiles\/(\d+)\/(\d+)\/(\d+)$/)) && m === "GET") { try { return send(res, 200, tile(ice, risk, Number(g[1]), Number(g[2]), Number(g[3]))); } catch (e) { return err(res, 404, (e as Error).message); } }
      if (p === "/v1/weather" && m === "GET") { const x = num(u.searchParams.get("x"), 100), y = num(u.searchParams.get("y"), 60), from = num(u.searchParams.get("from"), 0), to = num(u.searchParams.get("to"), HOURS - 1); if (![x, y, from, to].every(Number.isFinite) || from < 0 || to > HOURS - 1 || from > to) return err(res, 400, `x, y numbers and 0 <= from <= to <= ${HOURS - 1} are required`); return send(res, 200, { x, y, items: series(x, y).filter((w) => w.hour >= from && w.hour <= to) }); }
      if (p === "/v1/vehicles" && m === "GET") { const hour = num(u.searchParams.get("hour"), 0); if (!Number.isFinite(hour) || hour < 0 || hour > HOURS) return err(res, 400, `hour must be 0 to ${HOURS}`); return send(res, 200, { hour, items: VEHICLES.map((v) => ({ ...v, telemetry: sampleAt(tele[v.id], hour) })) }); }
      if ((g = p.match(/^\/v1\/vehicles\/([\w-]+)\/telemetry$/)) && m === "GET") { const s = tele[g[1]]; if (!s) return err(res, 404, "no such vehicle"); const from = num(u.searchParams.get("from"), 0), to = num(u.searchParams.get("to"), HOURS), limit = num(u.searchParams.get("limit"), 100), cursor = num(u.searchParams.get("cursor"), 0); if (!Number.isFinite(from) || !Number.isFinite(to) || !Number.isInteger(limit) || limit < 1 || limit > 500 || !Number.isInteger(cursor) || cursor < 0) return err(res, 400, "from and to are hours; limit 1-500 and cursor are whole numbers"); return send(res, 200, page(s, from, to, limit, cursor)); }
      if (p === "/v1/routes/plan" && m === "POST") {
        const key = req.headers["idempotency-key"]; if (typeof key !== "string" || !key) return err(res, 400, "Idempotency-Key header required"); if (seen.has(key)) return send(res, 200, seen.get(key));
        const b = await body(req), from = point(b.from ?? "A"), to = point(b.to ?? "D"); if (!from || !to) return err(res, 422, "from and to must be a camp id or [x, y] km inside the region"); const cand = typeof b.candidate === "string" ? CANDIDATES.find((c) => c.id === b.candidate) : null; if (typeof b.candidate === "string" && !cand) return err(res, 422, `candidate must be one of ${CANDIDATES.map((c) => c.id).join(", ")}`);
        const w = cand?.weights ?? { risk: b.weights?.risk ?? 0.5, support: b.weights?.support ?? 0.5 }, dep = b.departHour ?? DEFAULT_DEPART; if (![w.risk, w.support, dep].every((n) => typeof n === "number" && Number.isFinite(n)) || w.risk < 0 || w.risk > 1 || w.support < 0 || w.support > 1 || dep < 0 || dep > HOURS) return err(res, 422, `weights must be 0 to 1 and departHour 0 to ${HOURS}`);
        const r = plan(ice, risk, { id: `plan${seq}`, name: cand?.name ?? "Custom", weights: w }, from, to, dep); if (!r) return err(res, 409, "no crossable path between those points"); const out = { id: `plan${seq++}`, departHour: dep, route: r.route, metrics: r.metrics, start: { cell: cellOf(...from), centre: centerOf(...cellOf(...from)), riskHere: risk[idx(...cellOf(...from))] } }; plans.set(out.id, out); seen.set(key, out); return send(res, 201, out);
      }
      return err(res, 404, "not found");
    } catch (e) { return err(res, e instanceof SyntaxError || e instanceof RangeError ? 400 : 500, e instanceof Error ? e.message : "error"); }
  });
  const wss = new WebSocketServer({ noServer: true }); let timer: ReturnType<typeof setInterval> | null = null; let hour = 0;
  wss.on("connection", (ws) => { ws.send(JSON.stringify({ type: "hello", vehicles: VEHICLES.map((v) => v.id), speed: "1 hour per second" })); });
  server.on("upgrade", (req, socket, head) => { if (new URL(req.url ?? "/", "http://x").pathname.replace(/\/+$/, "") !== "/v1/vehicles/live") { socket.destroy(); return; } wss.handleUpgrade(req, socket, head, (ws) => wss.emit("connection", ws, req)); if (!timer) timer = setInterval(() => { hour = (hour + 0.25) % HOURS; for (const c of wss.clients) if (c.readyState === 1) for (const v of VEHICLES) c.send(JSON.stringify({ type: "telemetry", ...sampleAt(tele[v.id], hour), weather: weatherAt(sampleAt(tele[v.id], hour).x, sampleAt(tele[v.id], hour).y, hour).storm })); }, 250); });
  return { server, listen: (port = 8700) => new Promise<number>((r) => server.listen(port, () => r((server.address() as { port: number }).port))), close: () => new Promise<void>((r) => { if (timer) clearInterval(timer); for (const c of wss.clients) c.terminate(); wss.close(); server.closeAllConnections(); server.close(() => r()); }) };
}
if (import.meta.url === `file://${process.argv[1]}`) build().listen().then((p) => console.log(`POLARIS API on :${p}`));
