import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { build } from "../src/server.ts";
import { WebSocket } from "ws";
const api = build(); let base = "", port = 0;
beforeAll(async () => { port = await api.listen(0); base = `http://127.0.0.1:${port}`; }); afterAll(() => api.close());
type J = Record<string, any>;
const j = async (path: string, init?: RequestInit) => { const r = await fetch(base + path, init); return { status: r.status, body: (await r.json()) as J }; };
const post = (path: string, b: unknown, key: string | null) => j(path, { method: "POST", headers: { "content-type": "application/json", ...(key ? { "idempotency-key": key } : {}) }, body: JSON.stringify(b) });
describe("expedition and tiles", () => {
  it("returns the expedition with camps, rovers and three candidate routes with metrics", async () => { const e = (await j("/v1/expeditions/exp-2026-nordvik")).body; expect(e.camps).toHaveLength(5); expect(e.vehicles).toHaveLength(3); expect(e.routes.map((r: J) => r.id)).toEqual(["direct", "safe", "supported"]); expect(e.routes[1].metrics.minThicknessCm).toBeGreaterThan(e.routes[0].metrics.minThicknessCm); expect((await j("/v1/expeditions/nope")).status).toBe(404); });
  it("serves bounded ice tiles and rejects ones outside the pyramid", async () => { const t = (await j("/v1/ice/tiles/2/1/2")).body; expect(t.thicknessCm).toHaveLength(60); expect(t.risk).toHaveLength(60); expect(t.cellKm).toBe(5); expect((await j("/v1/ice/tiles/0/0/0")).body.cellKm).toBe(20); expect((await j("/v1/ice/tiles/3/0/0")).status).toBe(404); expect((await j("/v1/ice/tiles/1/2/0")).status).toBe(404); });
});
describe("weather and vehicles", () => {
  it("returns an hourly range and validates it", async () => { const w = (await j("/v1/weather?from=30&to=40")).body; expect(w.items).toHaveLength(11); expect(Math.max(...w.items.map((x: J) => x.storm))).toBeGreaterThan(0.9); expect((await j("/v1/weather?from=50&to=10")).status).toBe(400); expect((await j("/v1/weather?x=abc")).status).toBe(400); });
  it("lists rovers with telemetry at an hour, and pages one rover's telemetry", async () => { const v = (await j("/v1/vehicles?hour=40")).body; expect(v.items).toHaveLength(3); expect(v.items[0].telemetry.hour).toBeCloseTo(40, 0); expect((await j("/v1/vehicles?hour=99")).status).toBe(400); let cursor: number | null = 0, n = 0; while (cursor !== null) { const p: J = (await j(`/v1/vehicles/R1/telemetry?limit=200&cursor=${cursor}`)).body; n += p.items.length; cursor = p.nextCursor; expect(p.items.length).toBeLessThanOrEqual(200); } expect(n).toBe(433); expect((await j("/v1/vehicles/R9/telemetry")).status).toBe(404); expect((await j("/v1/vehicles/R1/telemetry?limit=9999")).status).toBe(400); });
});
describe("route planning", () => {
  it("plans a candidate, replays by key and refuses without a key", async () => { const a = await post("/v1/routes/plan", { candidate: "safe", departHour: 10 }, "k1"), b = await post("/v1/routes/plan", { candidate: "safe", departHour: 10 }, "k1"); expect(a.status).toBe(201); expect(a.body.route.points[0]).toEqual([20, 20]); expect(b.status).toBe(200); expect(b.body.id).toBe(a.body.id); expect((await post("/v1/routes/plan", {}, null)).status).toBe(400); });
  it("custom weights and endpoints work, and a later departure meets the storm", async () => { const early = (await post("/v1/routes/plan", { candidate: "direct", departHour: 0 }, "k2")).body, late = (await post("/v1/routes/plan", { candidate: "direct", departHour: 20 }, "k3")).body; expect(late.metrics.stormExposureH).toBeGreaterThan(early.metrics.stormExposureH); const c = await post("/v1/routes/plan", { from: "A", to: [150, 90], weights: { risk: 1, support: 0 } }, "k4"); expect(c.status).toBe(201); expect(c.body.route.points.at(-1)).toEqual([150, 90]); });
  it("validates inputs and names the problem", async () => { expect((await post("/v1/routes/plan", { from: "Z" }, "k5")).body.error).toMatch(/camp id/); expect((await post("/v1/routes/plan", { to: [999, 5] }, "k6")).status).toBe(422); expect((await post("/v1/routes/plan", { candidate: "fast" }, "k7")).body.error).toMatch(/candidate/); expect((await post("/v1/routes/plan", { weights: { risk: 5 } }, "k8")).status).toBe(422); expect((await j("/v1/routes/plan", { method: "POST", headers: { "idempotency-key": "bad" }, body: "{" })).status).toBe(400); expect((await j("/v1/routes/plan", { method: "POST", headers: { "idempotency-key": "big" }, body: JSON.stringify({ x: "a".repeat(11_000) }) })).status).toBe(400); });
  it("publishes OpenAPI 3.1 including the live channel, and answers health checks", async () => { const o = (await j("/openapi.json")).body; expect(o.openapi).toBe("3.1.0"); expect(Object.keys(o.paths)).toContain("/v1/vehicles/live"); expect((await j("/healthz")).body.ok).toBe(true); expect((await j("/nope")).status).toBe(404); });
});
describe("the live channel", () => {
  it("streams telemetry for every rover over a WebSocket", async () => { const msgs: J[] = await new Promise((resolve, reject) => { const ws = new WebSocket(`ws://127.0.0.1:${port}/v1/vehicles/live`), got: J[] = []; ws.on("message", (m) => { got.push(JSON.parse(String(m))); if (got.length >= 5) { ws.close(); resolve(got); } }); ws.on("error", reject); setTimeout(() => reject(new Error("no messages")), 5000); }); expect(msgs[0].type).toBe("hello"); const t = msgs.filter((m) => m.type === "telemetry"); expect(t.length).toBeGreaterThanOrEqual(3); expect(new Set(t.map((m) => m.vehicleId)).size).toBe(3); expect(t[0]).toHaveProperty("fuelPct"); });
  it("refuses an upgrade on any other path", async () => { await expect(new Promise((resolve, reject) => { const ws = new WebSocket(`ws://127.0.0.1:${port}/v1/other`); ws.on("open", () => resolve("open")); ws.on("error", reject); })).rejects.toBeTruthy(); });
});
